language: cpp
dist: trusty
sudo: required
os: linux

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Release STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - boost1.67
            
before_install:
  - pip install cmake
  - mkdir AMM_Modules/build && cd AMM_Modules/build
  - ../../travis_scripts/fastrtps.sh
  
script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - make

addons:
  apt:
    packages:      
      - libtinyxml2-dev
      - openjdk-8-jdk-headless
      - gradle      
