//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AMM.cpp
//  Source: ../../idl/AMM.idl
//  Generated: Fri May 12 16:08:19 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "AMM.h"




