//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AMM.cpp
//  Source: ../../../IDL/AMM.idl
//  Generated: Fri Jun  2 15:37:56 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "AMM.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < AMM::Performance::xAPIModifier, struct xAPI_Modifiers_uniq_>;
#endif



