//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AMM.h
//  Source: ../../idl/AMM.idl
//  Generated: Fri May 12 16:08:19 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _AMM_H_
#define _AMM_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace AMM
{
   namespace Simulation
   {
      struct Tick;

      struct Tick
      {
            DDS::LongLong frame;
            DDS::Float time;
      };

      typedef DDS_DCPSStruct_var < Tick> Tick_var;
      typedef Tick&Tick_out;
   }
   namespace Physiology
   {
      struct Data;
      struct HighFrequencyData;

      struct Data
      {
            DDS::String_mgr node_path;
            DDS::String_mgr unit;
            DDS::Double dbl;
            DDS::String_mgr str;
      };

      typedef DDS_DCPSStruct_var < Data> Data_var;
      typedef DDS_DCPSStruct_out < Data> Data_out;

      struct HighFrequencyData
      {
            DDS::String_mgr node_path;
            DDS::String_mgr unit;
            DDS::Double dbl;
            DDS::String_mgr str;
      };

      typedef DDS_DCPSStruct_var < HighFrequencyData> HighFrequencyData_var;
      typedef DDS_DCPSStruct_out < HighFrequencyData> HighFrequencyData_out;
   }
}




#endif 
