# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(PICFLAGS) $(GENFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -pthread -D_REENTRANT -I"." -I"$(BIOGEARS_ROOT)/library/include" -I"$(BIOGEARS_ROOT)/library/include/cdm" -I"$(BIOGEARS_ROOT)/library/include/log4cpp" -I"$(BIOGEARS_ROOT)/library/include/Eigen" -I"$(BIOGEARS_ROOT)/library/include/bind" -I"$(OSPL_HOME)/include" -I"$(OSPL_HOME)/include/sys" -I"$(OSPL_HOME)/include/dcps/C++/SACPP"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
CCC           = $(CXX)
MAKEFILE      = Makefile.amm_physiology_manager
DEPENDENCIES  = $(MAKEFILE)
BTARGETDIR    = ../../bin/
LDFLAGS       = -L"." -L"$(BTARGETDIR)" -L"$(OSPL_HOME)/lib" -Wl,-rpath,$(BIOGEARS_ROOT)/library/lib
BIN           = $(BTARGETDIR)amm_physiology_manager$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -std=c++11
LDLIBS        = -ldcpssacpp -lddskernel -ldl -Wl,-rpath,$(BIOGEARS_ROOT)/library/lib $(BIOGEARS_ROOT)/library/lib/libxerces-c.so $(BIOGEARS_ROOT)/library/lib/BioGearsEngine.so $(BIOGEARS_ROOT)/library/lib/DataModelBindings.so $(BIOGEARS_ROOT)/library/lib/CommonDataModel.so $(BIOGEARS_ROOT)/library/lib/liblog4cpp.so -l"amm_types$(LIBSUFFIX)" -lpthread 
OBJS          = .obj$(CFG)/CheckStatus$(OBJEXT) .obj$(CFG)/DDSEntityManager$(OBJEXT) .obj$(CFG)/BioGearsThread$(OBJEXT) .obj$(CFG)/PhysiologyEngineManager$(OBJEXT) .obj$(CFG)/TickDataListener$(OBJEXT) .obj$(CFG)/PhysiologyManager$(OBJEXT)
SRC           =  ../src/AMM/CheckStatus.cpp ../src/AMM/DDSEntityManager.cpp ../src/AMM/BioGearsThread.cpp ../src/AMM/PhysiologyEngineManager.cpp ../src/AMM/TickDataListener.cpp ../src/PhysiologyManager.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN) deploy

$(BIN): $(OBJS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

.obj$(CFG)/PhysiologyManager$(OBJEXT): ../src/PhysiologyManager.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/PhysiologyManager.cpp

.obj$(CFG)/PhysiologyEngineManager$(OBJEXT): ../src/AMM/PhysiologyEngineManager.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/AMM/PhysiologyEngineManager.cpp
	
.obj$(CFG)/TickDataListener$(OBJEXT): ../src/AMM/TickDataListener.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/AMM/TickDataListener.cpp

.obj$(CFG)/BioGearsThread$(OBJEXT): ../src/AMM/BioGearsThread.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/AMM/BioGearsThread.cpp
		
.obj$(CFG)/CheckStatus$(OBJEXT): ../src/AMM/CheckStatus.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/AMM/CheckStatus.cpp

.obj$(CFG)/DDSEntityManager$(OBJEXT): ../src/AMM/DDSEntityManager.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/AMM/DDSEntityManager.cpp

deploy: 
	-$(CP) -r ../../support/config $(BTARGETDIR)
	-$(CP) -r ../../support/patients $(BTARGETDIR)
	-$(CP) -r ../../support/environments $(BTARGETDIR)
	-$(CP) -r ../../support/nutrition $(BTARGETDIR)
	-$(CP) -r ../../support/ecg $(BTARGETDIR)
	-$(CP) -r ../../support/substances $(BTARGETDIR)
	-$(CP) -r $(BIOGEARS_ROOT)/library/bin/xsd $(BTARGETDIR)
	-$(CP) -r $(BIOGEARS_ROOT)/library/bin/UCEDefs.txt $(BTARGETDIR)
	-$(CP) -r ../../support/log4j.properties $(BTARGETDIR)
	-$(CP) -r ../../support/BioGearsConfiguration.xml $(BTARGETDIR)
	-$(CP) -r ../../support/Actions $(BTARGETDIR)
	-$(CP) -r ../../support/states $(BTARGETDIR)
	-$(CP) -r ../../support/ecg $(BTARGETDIR)

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) .obj$(CFG)/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

